sudo: false
language: node_js

node_js:
 - 7.6

branches:
  except:
    - v0

env:
  global:
    - ISTANBUL_COVERAGE: yes

script:
 - yarn bootstrap
 - yarn lint
 - yarn test:webpack-1
 - yarn test:webpack-2

after_success:
 - yarn upload-coverage
 - yarn release
